### ISSUE TITLE
api and typesense containers crash - AVX issue too?

### ISSUE THREAD

**Issue by working-name** [julianpoy/RecipeSage-selfhost#68]
Hello,

Trying to get the stack up for the first time. I'm not enabling ingredient classifier container because no AVX (old intel xeon).

typesense:
```py
recipesage_typesense exited with code 0
recipesage_typesense    | E20240108 17:11:36.163722     7 backward.hpp:4199] Stack trace (most recent call last) in thread 7:
recipesage_typesense    | E20240108 17:11:36.163761     7 backward.hpp:4199] #7    Object "", at 0xffffffffffffffff, in
recipesage_typesense    | E20240108 17:11:36.163769     7 backward.hpp:4199] #6    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fc5de6a7bb3, in __clone
recipesage_typesense    | E20240108 17:11:36.163776     7 backward.hpp:4199] #5    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fc5de616b42, in
recipesage_typesense    | E20240108 17:11:36.163794     7 backward.hpp:4199] #4    Object "/opt/typesense-server", at 0x84d418, in bvar::detail::SamplerCollector::sampling_thread(void*)
recipesage_typesense    | E20240108 17:11:36.163801     7 backward.hpp:4199] #3    Object "/opt/typesense-server", at 0x84b908, in bvar::detail::SamplerCollector::run()
recipesage_typesense    | E20240108 17:11:36.163808     7 backward.hpp:4199] #2  | Source "/usr/local/include/bvar/passive_status.h", line 62, in get_value
recipesage_typesense    | E20240108 17:11:36.163815     7 backward.hpp:4199]       Source "/usr/local/include/bvar/passive_status.h", line 140, in take_sample [0x7a4413]
recipesage_typesense    | E20240108 17:11:36.163821     7 backward.hpp:4199] #1    Source "/opt/braft-80d97b2475b3c0afca79c19b64d46bb665d704f4/src/braft/util.cpp", line 215, in counter_percentile [0x7e18cf]
recipesage_typesense    | E20240108 17:11:36.163828     7 backward.hpp:4199] #0    Source "/usr/local/include/bvar/detail/percentile.h", line 294, in snprintf [0x7e52d5]
recipesage_typesense    | Illegal instruction (Illegal operand [0x7e52d5])
recipesage_typesense    | E20240108 17:11:36.273038     7 typesense_server.cpp:102] Typesense 0.24.1 is terminating abruptly.
```

api:
```py
0 verbose cli /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 20ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 44ms
6 timing config:load:builtin Completed in 44ms
7 timing config:load:cli Completed in 45ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/app/.npmrc Completed in 0ms
10 timing config:load:project Completed in 7ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 105ms
17 timing npm:load:configload Completed in 105ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm exec ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www
21 verbose argv "exec" "--" "ts-node" "--swc" "--project" "packages/backend/tsconfig.json" "packages/backend/src/bin/www"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 13ms
24 timing npm:load:display Completed in 15ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-01-08T17_04_39_687Z-
26 verbose logfile /root/.npm/_logs/2024-01-08T17_04_39_687Z-debug-0.log
27 timing npm:load:logFile Completed in 49ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 194ms
31 silly logfile done cleaning log files
32 timing command:exec Completed in 7933ms
33 verbose stack Error: command failed
33 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
33 verbose stack     at ChildProcess.emit (node:events:513:28)
33 verbose stack     at maybeClose (node:internal/child_process:1091:16)
33 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
34 verbose pkgid recipesage@0.0.0
35 verbose cwd /app
36 verbose Linux 6.1.0-0.deb11.13-amd64
37 verbose node v18.16.0
38 verbose npm  v9.5.1
39 error path /app
40 error command failed
41 error signal SIGILL
42 error command sh -c ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www
43 verbose exit 1
44 timing npm Completed in 8174ms
45 verbose code 1
46 error A complete log of this run can be found in:
46 error     /root/.npm/_logs/2024-01-08T17_04_39_687Z-debug-0.log
```

Docker version 24.0.7, build afdd53b
Docker Compose version v2.21.0
Debian GNU/Linux 11 (bullseye)

docker-compose.yml:
```yaml
version: '3.7'
services:
  proxy: # The proxy must not be removed. If needed, point your own proxy to this container, rather than removing this
    container_name: recipesage_proxy
    image: nginx
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 127.0.0.1:18085:80
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
  static: # Hosts frontend assets
    container_name: recipesage_static
    image: julianpoy/recipesage-selfhost:static-v2.12.10
    restart: unless-stopped
  api: # Hosts backend API
    container_name: recipesage_api
    image: julianpoy/recipesage-selfhost:api-v2.12.10
    depends_on:
      - postgres
      - typesense
      - pushpin
      - browserless
    command: npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www
    environment:
      - STORAGE_TYPE=filesystem
      - FILESYSTEM_STORAGE_PATH=/rs-media
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - DATABASE_URL=postgresql://recipesage_selfhost:recipesage_selfhost@postgres:5432/recipesage_selfhost
      - GCM_KEYPAIR
      - SENTRY_DSN
      - GRIP_URL=http://pushpin:5561/
      - GRIP_KEY=changeme
      - SEARCH_PROVIDER=typesense
      - 'TYPESENSE_NODES=[{"host": "typesense", "port": 8108, "protocol": "http"}]'
      - TYPESENSE_API_KEY=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3000/
    volumes:
      - ./apimedia:/rs-media
    restart: unless-stopped
  typesense:
    container_name: recipesage_typesense
    image: typesense/typesense:0.24.1
    volumes:
      - ./typesensedata:/data
    command: "--data-dir /data --api-key=recipesage_selfhost --enable-cors"
    restart: unless-stopped
  pushpin: # Provides websocket support
    container_name: recipesage_pushpin
    image: julianpoy/pushpin:2023-09-17
    entrypoint: /bin/sh -c
    command:
      [
        'sed -i "s/sig_key=changeme/sig_key=$$GRIP_KEY/" /etc/pushpin/pushpin.conf && echo "* $${TARGET},over_http" > /etc/pushpin/routes && pushpin --merge-output',
      ]
    environment:
      - GRIP_KEY=changeme
      - TARGET=api:3000
    restart: unless-stopped
  postgres: # Database
    container_name: recipesage_postgres
    image: postgres:16
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1g"
    environment:
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: unless-stopped
  browserless: # A headless browser for scraping websites with the auto import tool
    container_name: recipesage_browserless
    image: browserless/chrome:1.57-puppeteer-19.2.2
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped
  # ingredient-instruction-classifier: # A mini server that runs a machine learning model able to classify text for improved automatic import
  #   container_name: recipesage_classifier
  #   image: julianpoy/ingredient-instruction-classifier:1.4.9
  #   environment:
  #     - SENTENCE_EMBEDDING_BATCH_SIZE=200
  #     - PREDICTION_CONCURRENCY=4
  #   restart: unless-stopped
volumes:
  apimedia:
    driver: local
  typesensedata:
    driver: local
  postgresdata:
    driver: local
```
